# This file should be in the ROOT of your project repository.

[build]
  # Base directory: The directory to change to before starting the build.
  # We will run the build from within the 'dev' folder.
  base = "dev"

  # Build command: This command is run from within the base directory ('dev').
  # It will install dependencies, create the 'public' directory, and then
  # run the ejs-test.js script to generate the index.html file.
  command = "npm install && mkdir -p public && node ./test/ejs-test.js"

  # Publish directory: The directory that contains the built site files.
  # Since the base is 'dev', Netlify will look for 'dev/public'.
  publish = "public"

  # Functions directory: Location of your serverless functions,
  # relative to the base directory.
  functions = "netlify/functions"

# Optional: You can specify a Node.js version to prevent build issues.
[build.environment]
  NODE_VERSION = "18"
