[build]
  base = "dev"
  command = "npm install && mkdir -p public && echo '<h1>FFIEC Functions Active</h1><p>Functions deployed successfully</p>' > public/index.html"
  publish = "public"
  functions = "netlify/functions"

[functions]
  # Global function settings
  timeout = 30
  memory = 1024

[functions.ffiec]
  timeout = 30
  memory = 1024

[functions.fred]
  timeout = 15
  memory = 512

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"
    Cache-Control = "public, max-age=300"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
