[build]
  functions = "netlify/functions"

[functions]
  # Use esbuild bundler for all functions
  node_bundler = "esbuild"

[functions.ffiec]
  # Increase timeout for the FFIEC function
  timeout = 60

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Add CORS headers for all API requests
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    "Access-Control-Allow-Origin" = "*"
    "Access-Control-Allow-Headers" = "Content-Type, Authorization"
    "Access-Control-Allow-Methods" = "GET, POST, OPTIONS"
    "Access-Control-Max-Age" = "86400"
